controller_manager:
  ros__parameters:
    update_rate: 10  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    ackermann_steering_controller:
      type: ackermann_steering_controller/AckermannSteeringController

# no config for joint_state_broadcaster

ackermann_steering_controller:
  ros__parameters:

    reference_timeout: 2.0
    front_steering: true
    open_loop: false
    velocity_rolling_window_size: 10
    position_feedback: true
    use_stamped_vel: true
    rear_wheels_names: [right_rear_wheel_joint, left_rear_wheel_joint]
    front_wheels_names: [right_steering_hinge_joint, left_steering_hinge_joint]

    wheelbase: 0.325
    front_wheel_track: 0.2
    rear_wheel_track: 0.2
    front_wheels_radius: 0.05
    rear_wheels_radius: 0.05